language: groovy

jdk:
  - oraclejdk7
# only really need to test with one version of Java, Moqui is tested with various
#  - openjdk7
# runs slowly and often fails due to insufficient wait times in tests, found JDK8 to be faster than JDK7 in other environments, commenting for now:
#  - oraclejdk8

install: true

before_script:
  - cd ..
  - git clone https://github.com/moqui/moqui-framework.git moqui
  - cd moqui

env:
  - TERM=dumb

script:
  - gradle getGit -Pcomponent=mantle-usl
  - gradle load
  - gradle runtime/mantle/mantle-usl:test --info
