language: groovy

sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
#  - oraclejdk7
#  - openjdk7
  - oraclejdk8

install: true

before_script:
  - cd ..
  - git clone https://github.com/moqui/moqui-framework.git moqui
  - cd moqui

env:
  - TERM=dumb

script:
  - gradle getGit -Pcomponent=mantle-usl
  - gradle load
  - gradle runtime/component/mantle-usl:test --info

cache:
  directories:
    - $HOME/.gradle/caches
